services:
  - postgresql
before_script:
  - psql -c 'create database zooka-watersports;' -U postgres
env:
  - ACCESS_TOKEN_EXPIRES=900 REFRESH_TOKEN_EXPIRES=2592000
language: python
python:
  - "3.7"
install:
  - "pip install -r restapi/requirements.txt"
before_script:
  - cd restapi/
  - export FLASK_APP=app.py
  - flask db init
  - flask db migrate -m "init db"
  - flask db upgrade
  - cd services/tests/system
script: pytest -v
