env:
  - ACCESS_TOKEN_EXPIRES=900
  - REFRESH_TOKEN_EXPIRES=2592000
language: python
python:
  - "3.7"
  - "nightly"
install:
  - "pip install -r restapi/requirements.txt"
before_script: cd restapi/services/tests/system
script: pytest -v
